version: "3.3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:development-v6
    hostname: piholev6
    volumes:
      - 'pihole:/etc/pihole/'
      - 'dnsmasq.d:/etc/dnsmasq.d/'
    depends_on:
      - unbound
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
      - NET_RAW
        - SYS_NICE
      - CHOWN
    restart: unless-stopped
    network_mode: "host"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - homepage.group=Containers
      - homepage.name=PiHole v6
      - homepage.href=http://192.269.1.202:8084/admin/
      - homepage.description=PiHole v6 Beta Service
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=development-v6"

  unbound:
    restart: unless-stopped
    container_name: unbound
    image: cdrocker/unbound:latest
    volumes:
      - 'unbound-data:/etc/unbound/conf.d/'
    network_mode: "host"
    cap_add:
     - NET_ADMIN
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"

volumes:
  pihole:
  dnsmasq.d:
  unbound-data:
