#version: "3.3"

services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    hostname: homeassistant
    privileged: true
    network_mode: "host"
    environment:
      TZ: 'Europe/London'
      DISABLE_JEMALLOC: 'true'
    volumes:
      - 'hass_config:/config'
      - '/run/dbus:/run/dbus:ro'
      - '/etc/localtime:/etc/localtime:ro'
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - homepage.group=Containers
      - homepage.name=Homeassistant
      - homepage.href=http://homeassistant.lan/
      - homepage.description=Homeassistant Manager Service

volumes:
  hass_config:
