# Pi-Hole - https://pi-hole.net
version: "3.9"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8192:8192"
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/resolv.conf:/etc/resolv.conf:ro
      - 'pihole:/etc/pihole/'
      - 'addon:/usr/local/share/bin/'
      - 'dnsmasq.d:/etc/dnsmasq.d/'
    environment:
      - TZ=Europe/London
      - REV_SERVER=true
      - REV_SERVER_DOMAIN=home.arpa
      - REV_SERVER_TARGET=192.168.1.1
      - REV_SERVER_CIDR=192.168.1.0/24
      - DHCP_ACTIVE=true
      - DHCP_END=192.168.1.200
      - DHCP_IPv6=false
      - DHCP_LEASETIME=24
      - DHCP_rapid_commit=true
      - DHCP_ROUTER=192.168.1.1
      - DHCP_START=192.168.1.10
      - DNSMASQ_LISTENING=all
      - PIHOLE_DNS_=9.9.9.10;149.112.112.10
      - DNSSEC="false"
      - PIHOLE_DOMAIN=home.arpa
      - FTLCONF_LOCAL_IPV4=192.168.1.201
      - VIRTUAL_HOST=pihole.apps.home.arpa
      - WEB_PORT=8192
      - WEB_BIND_ADDR=0.0.0.0
      - IPv6=false
    restart: unless-stopped
    labels:
      - autoheal=true
      - "com.centurylinklabs.watchtower.enable=false"
      - homepage.group=Containers
      - homepage.name=Pi-hole
      - homepage.href=http://pihole.apps.home.arpa/admin/
      - homepage.description=Pi-hole Network-wide Ad Blocking
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"
      - "traefik.enable=true"
      - "traefik.backend=pihole"
      - "traefik.port=8192"
      - traefik.http.routers.pihole.rule=Host(`pihole.apps.home.arpa`)
      - "traefik.http.services.pihole.loadbalancer.server.port=8192"
      - "traefik.http.routers.pihole.entrypoints=web"

volumes:
  pihole:
  dnsmasq.d:
  addon:

networks:
  proxy:
    external: true
