# Memcached - https://www.memcached.org
version: "3.9"

services:
  redis:
   image: redis:alpine
   container_name: redis
   restart: unless-stopped
   volumes:
      - "conf:/usr/local/etc/redis"
      - "cache:/data"
   expose:
     - "6379:6379"
   labels:
     - "diun.enable=true"
     - "diun.watch_repo=true"
     - "diun.include_tags=alpine"

volumes:
  conf:
  cache:
