version: "3.9"

services:
  pihole:
    env_file:
      - ${DOCKER_ENV}/pihole-v6.env
    container_name: pihole
    image: pihole/pihole:development-v6
    hostname: piholev6
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3008:80/tcp"
    volumes:
      - 'pihole:/etc/pihole/'
      - 'dnsmasq.d:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
      - NET_RAW
      - SYS_NICE
      - CHOWN
    restart: unless-stopped
    networks:
      backend:
       ipv4_address: '172.31.0.100'
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - homepage.group=Containers
      - homepage.name=PiHole v6
      - homepage.href=http://192.269.1.202:8084/admin/
      - homepage.description=PiHole v6 Beta Service
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=development-v6"

networks:
  backend:
    ipam:
      config:
        - subnet: 172.31.0.0/16

volumes:
  pihole:
  dnsmasq.d:

