version: "3.3"

services:
  gotify:
    image: gotify/server-arm64:latest
    container_name: gotify
    restart: unless-stopped
    ports:
      - 3004:80
    volumes:
      - "gotify-data:/app/data"
    labels:
      - homepage.group=Containers
      - homepage.name=Gotify
      - homepage.href=http://gotify.lan
      - homepage.description=Gotify Notification Service
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"

volumes:
  gotify-data:
