version: "3.3"

services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    restart: unless-stopped
    volumes:
      - gitea-git-data:/data
    ports:
      - 3003:3000
    depends_on:
     - db
    labels:
      - homepage.group=Containers
      - homepage.name=Gitea
      - homepage.href=http://gitea.lan/
      - homepage.description=Gitea Service
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    restart: unless-stopped
    volumes:
      - gitea-db-data:/var/lib/postgresql/data
    expose:
        - 5432
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=alpine"

volumes:
  gitea-db-data:
  gitea-git-data:
