# Caddy - https://www.caddysever.com / 
version: "3.9"

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    restart: unless-stopped
    labels:
      - homepage.group=Containers
      - homepage.name=Caddy
      - homepage.href=https://www.caddyserver.com/
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"

volumes:
  caddy_config:
  caddy_data:
