version: "3.3"

services:
  adguardhome:
    image: adguard/adguardhome:latest
    restart: unless-stopped
    container_name: adguardhome
    command: "-p 3000 -c /opt/adguardhome/conf/AdGuardHome.yaml"
    network_mode: "host"
    environment:
      TZ: 'Europe/London'
    volumes:
      - "adguardhome_data:/opt/adguardhome/data"
      - "adguardhome_conf:/opt/adguardhome/conf"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - homepage.group=Containers
      - homepage.name=Adguard Home Ad Blocker
      - homepage.href=http://adguardhome.lan
      - homepage.description=AdGuard Home edition service

volumes:
  adguardhome_data:
  adguardhome_conf:
