#version: "3.3"

services:
  openhab:
    env_file:
      - ${DOCKER_ENV}/openhab.env
    container_name: openhab
    image: openhab/openhab:latest-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - homepage.group=Containers
      - homepage.name=OpenHAB
      - homepage.href=http://pihole.lan/admin/
      - homepage.description=OpenHAB Home Automation Service
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest-alpine"
    network_mode: "host"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "addons:/openhab/addons"
      - "conf:/openhab/conf"
      - "userdata:/openhab/userdata"

volumes:
  addons:
  conf:
  userdata:

