version: "3.5"
services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=alpine"

  linkwarden:
    container_name: linkwarden
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: unless-stopped
    image: ghcr.io/linkwarden/linkwarden:latest
    ports:
      - 3015:3000
    volumes:
      - data:/data/data
    depends_on:
      - postgres
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"
      - homepage.group=Containers
      - homepage.name=Limkwarden
      - homepage.href=http://limkwarden.lan
      - homepage.description=Linkwarden webpage management service
volumes:
  data:
  pgdata:
