#version: "3.9"

services:
  pihole:
    env_file:
      - ${DOCKER_ENV}/pihole.env
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    volumes:
      - 'pihole:/etc/pihole/'
      - 'dnsmasq.d:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
      - NET_RAW
      - SYS_NICE
      - CHOWN
    restart: unless-stopped
    network_mode: 'host'
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - homepage.group=Containers
      - homepage.name=PiHole
      - homepage.href=http://pihole.lan/admin/
      - homepage.description=PiHole Service
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"

volumes:
  pihole:
  dnsmasq.d:

