version: "3.3"

services:
  ciao:
    image: brotandgames/ciao:latest
    container_name: ciao
    restart: unless-stopped
    ports:
      - '3001:3000'
    environment:
      - SECRET_KEY_BASE=baad3cf6-47df-43c0-8f7c-6ade1ee13b9d
      - TZ=Eurooe/London
    volumes:
      - "ciao-data:/app/db/sqlite/"
    labels:
      - homepage.group=Containers
      - homepage.name=Ciao
      - homepage.href=http://ciao.lan
      - homepage.description=Ciao Service
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"

volumes:
  ciao-data:
