# Prometheus - https://prometheus.io/
version: "3.9"

services:
  prometheus:
    image: prom/prometheus :latest
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    volumes:
      - config:/etc/prometheus/
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    environment:
    labels:
      - homepage.group=Containers
      - homepage.name=Prometheus
      - homepage.href=
      - homepage.description=Prometheus Service
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"
      - "com.centurylinklabs.watchtower.enable=false"

volumes:
  config:
  prometheus-data:
