# Metube - https://github.com/alexta69/metube
version: "3.9"

services:
  metube:
    image: ghcr.io/alexta69/metube:latest
    container_name: metube
    restart: unless-stopped
    environment:
      - UID:${PUID}
      - GID:${PGID}
      - TZ:${TZ}
    ports:
      - "3014:8081"
    volumes:
      - /media/external/.ydl:/downloads
    labels:
      - homepage.group=Containers
      - homepage.name=Metube
      - homepage.href=http://192.168.1.201:3014
      - homepage.description=Metube Service
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"
      - "com.centurylinklabs.watchtower.enable=true"
