version: "3.9"

services:
  your_spotify:
    image: lscr.io/linuxserver/your_spotify:latest
    container_name: your_spotify
    hostname: your_spotify
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - APP_URL=http://192.168.1.201:3080
      - SPOTIFY_PUBLIC=
      - SPOTIFY_SECRET=
      - CORS=all
      - MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
    ports:
      - 3080:80
      - 3443:443
    restart: unless-stopped
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"

  mongo:
    container_name: mongo
    image: mongo:6
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db:
