version: "3.3"

services:
  adguardhome:
    image: adguard/adguardhome:latest
    restart: unless-stopped
     container_name: adguardhome
     network_mode: "host"
ķ    environment:
      TZ: 'Europe/London'
    volumes:
      - "adguardhome_data:/opt/adguardhome/work"
      - "adguardhome_conf:/opt/adguardhome/conf"
    label
      - h
omepage.group=Containers
      - homepage.name=Adguard Home Ad Blocker
      - homepage.href=http://adguardhome.lan
      - homepage.description=AdGuard Home edition service

volumes:
  adguardhome_data:
  adguardhoke_conf:
