# Mealie - https://mealie.io
version: "3.9"

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    hostname: mealie
    ports:
        - "3023:9000"
        - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - mealie_data:/app/data/
    environment:
      - ALLOW_SIGNUP=false
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=http://mealie.lan
      - SMTP_HOST=${MEALIE_SMTP_HOST}
      - SMTP_AUTH_STRATEGY=NONE
      - SMTP_FROM_EMAIL=${MEALIE_SMTP_FROM_EMAIL}
    restart: unless-stopped
    labels:
      - homepage.group=Containers
      - homepage.name=Mealie
      - homepage.href=http://mealie.lan
      - homepage.description=Recipie Database and Meal Planner
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"

volumes:
  mealie_data:
