# Unbound DNS Server - https://hub.docker.com/r/cdrocker/unbound
version: "3.9"

services:
  unbound-dns-a:
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    container_name: unbound-dns-a
    image: cdrocker/unbound:latest
    volumes:
      - 'unbound-a-data:/etc/unbound/conf.d/'
    ports:
      - "5300:5300/udp"
      - "5300:5300/tcp"
    cap_add:
      - NET_ADMIN
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"

#  unbound-dns-b:
#    environment:
#      - TZ=${TZ}
#    restart: unless-stopped
#    container_name: unbound-dns-b
#    image: cdrocker/unbound:latest
#    volumes:
#      - 'unbound-b-data:/etc/unbound/conf.d/'
#    ports:
#      - "5301:5300/udp"
#      - "5301:5300/tcp"
#    cap_add:
#      - NET_ADMIN
#    labels:
#      - "com.centurylinklabs.watchtower.enable=false"
#      - "diun.enable=true"
#      - "diun.watch_repo=true"
#      - "diun.include_tags=latest"

volumes:
  unbound-a-data:
#  unbound-b-data:


