version: "3.3"

services:
  unbound:
    restart: unless-stopped
    container_name: unbound
    image: cdrocker/unbound:latest
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    cap_add:
      - NET_ADMIN
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
