# SyncThing - https://hub.docker.com/r/linuxserver/syncthing
version: "3.9"

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - config:/config
      - $HOME/syncthing:/data_user
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    labels:
      - homepage.group=Containers
      - homepage.name=Syncthing
      - homepage.href=http://192.168.1.201:8384
      - homepage.description=Syncthing Syncronisation  Service
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"

volumes:
  config:
