version: "3.9"

services:
  gogs:
    env_file:
      - ${DOCKER_ENV}/gogs.env
    image: gogs/gogs:latest
    container_name: gogs
    restart: unless-stopped
    ports:
      - '3013:3000'
      - '10022:22'
    depends_on:
     - db
    volumes:
      - "gogs-data:/data"
    labels:
      - homepage.group=Containers
      - homepage.name=Gogs
      - homepage.href=http://gogs.lan
      - homepage.description=Gogs Git Version Control
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"

  db:
   image: postgres:alpine
   env_file:
     - ${DOCKER_ENV}/gogs.env
   restart: unless-stopped
   volumes:
     - gogs-db-data:/var/lib/postgresql/data
   expose:
     - 5432
   labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=alpine"

volumes:
  gogs-data:
  gogs-db-data:
