# PostgreSQL - https://www.postgresql.org
version: "3.9"

services:
  db:
   image: postgres:alpine
   container_name: postgres
   restart: unless-stopped
   volumes:
     - db-data:/var/lib/postgresql/data
   environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
   expose:
     - 5432
   labels:
     - "diun.enable=true"
     - "diun.watch_repo=true"
     - "diun.include_tags=alpine"

volumes:
  db-data:
