# Code Server - https://hub.docker.com/r/linuxserver/code-server
version: "3.9"

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - code_config:/config
    ports:
      - "3006:8443"
    restart: unless-stopped
    labels:
       - homepage.group=Containers
       - homepage.name=Code Server
       - homepage.href=http://openvscode.lan
       - homepage.description=Code as a Web App
       - "diun.enable=true"
       - "diun.watch_repo=true"
       - "diun.include_tags=latest"

volumes:
  code_config:
