version: "3.3"

services:
  neo4j:
    env_file:
      - ${DOCKER_ENV}/neo4j.env
   image: neo4j:enterprise
   container_name: neo4j
   restart: unless-stopped
   volumes:
     - neo4j-data:/data
   ports:
     - "7474:7474"
     - "7687:7687"
   labels:
     - "diun.enable=true"
     - "diun.watch_repo=true"
     - "diun.include_tags=enterprise"

volumes:
  neo4j-data:
