# Memcached - https://www.memcached.org
version: "3.9"

services:
  memcached:
   image: memcached:alpine
   container_name: memcached
   restart: unless-stopped
   expose:
     - "11211:11211"
   labels:
     - "diun.enable=true"
     - "diun.watch_repo=true"
     - "diun.include_tags=alpine"
