version: "3.9"

services:
  smtprelay:
    container_name: smtprelay
    hostname: smtprelay
    image: ixdotai/smtp:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:25:25"
    environment:
      - GMAIL_USER=${SMTP_GMAIL_USER}
      - GMAIL_PASSWORD=${SMTP_GMAIL_PASSWORD}
    labels:
      - homepage.group=Containers
      - homepage.name=SMTP
      - homepage.description=SMTP Relay Service
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"
