version: "3.3"

services:
  diun:
    env_file:
      - ${DOCKER_ENV}/diun.env
    image: crazymax/diun:latest
    command: serve
    hostname: diun
    container_name: diun
    volumes:
      - "data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"
    restart: unless-stopped

volumes:
  data:
