# Metube - https://github.com/alexta69/metube
version: "3.9"

services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    environment:
      - UID:${PUID}
      - GID:${PGID}
      - TZ:${TZ}
    ports:
      - "3014:8081"
    volumes:
      - /media/external/.ydl:/downloads
