version: "3.3"
name: "pihole-stack"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:development-v6
    hostname: piholev6
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3008:80/tcp"
    environment:
      TZ: 'Europe/London'
      FTLCONF_dhcp_active: 'false'
      FTLCONF_dhcp_end: '192.168.1.200'
      FTLCONF_dhcp_netmask: '255.255.255.0'
      FTLCONF_dhcp_ipv6: 'false'
      FTLCONF_dhcp_leaseTime : 24
      FTLCONF_dhcp_rapidCommit: 'true'
      FTLCONF_dhcp_router: '192.168.1.1'
      FTLCONF_dhcp_start: '192.168.1.10'
      FTLCONF_dns_listeningMode: "all"
      FTLCONF_dns_upstreams: "9.9.9.10;149.112.112.10"
      FTLCONF_dns_domain: "lan"
      ServerIP: '192.168.1.201'
      VIRTUAL_HOST: 'piholev6.lan'
      FTLCONF_webserver_api_password: ${DOCKER_CONTAINER_PWD}
      IPv6: "false"
    volumes:
      - 'pihole:/etc/pihole/'
      - 'dnsmasq.d:/etc/dnsmasq.d/'
    depends_on:
      - dhcphelper
      - unbound
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
      - NET_RAW
        - SYS_NICE
      - CHOWN
    restart: unless-stopped
    networks:
      backend:
       ipv4_address: '172.31.0.100'
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - homepage.group=Containers
      - homepage.name=PiHole v6
      - homepage.href=http://192.269.1.202:8084/admin/
      - homepage.description=PiHole v6 Beta Service

  unbound:
    restart: unless-stopped
    container_name: unbound
    image: cdrocker/unbound:latest
    volumes:
      - 'unbound-data:/etc/unbound/conf.d/'
    ports:
      - "5300:5300/udp"
      - "5300:5300/tcp"
    cap_add:
     - NET_ADMIN
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  dhcphelper:
    restart: unless-stopped
    container_name: dhcphelper
    network_mode: "host"
    image: homeall/dhcphelper:latest
    environment:
      TZ: 'Europe/London'
      IP: '172.31.0.100'
    cap_add:
      - NET_ADMIN
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

networks:
  backend:
    ipam:
      config:
        - subnet: 172.31.0.0/16

volumes:
  pihole:
  dnsmasq.d:
  unbound-data:
