version: "3.9"

services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest
    hostname: speedtestr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DB_CONNECTION=sqlite
      - APP_KEY=${SPEEDTEST_APP_KEY}
    volumes:
      - speedtest_config:/config
    ports:
      - 3024:80
    restart: unless-stopped
    labels:
      - homepage.group=Containers
      - homepage.name=Speedtest
      - homepage.href=http://speedtest.lan
      - homepage.description=Ookla Speedtest Service
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"

volumes:
  speedtest_config:
