version: '3.9'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - prometheus_config:/etc/prometheus/:ro
      - prometheus_data:/prometheus
    restart: unless-stopped
    labels:
      - homepage.group=Containers
      - homepage.name=Prometheus
      - homepage.href=http://192.168.1.201:9090
      - homepage.description=Prometheus Service
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"
      - "com.centurylinklabs.watchtower.enable=true"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=http://grafana.lan
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-clock-panel
    labels:
      - homepage.group=Containers
      - homepage.name=Grafana
      - homepage.href=http://grafana.lan
      - homepage.description=Grafana Service
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"
      - "com.centurylinklabs.watchtower.enable=true"

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command: '--path.rootfs=/host'
    pid: host
    ports:
       - 9100:9100
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
    labels:
      - homepage.group=Containers
      - homepage.name=Node Exporter
      - homepage.description=Node Exporter Service
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"
      - "com.centurylinklabs.watchtower.enable=true"

  cadvisor:
    image: d3vilh/cadvisor:latest
    container_name: cadvisor
    command:
      - '-port=8098'
    ports:
      - '8098:8098'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped
    labels:
      - homepage.group=Containers
      - homepage.name=CAdvisor
      - homepage.href=http://192.168.1.201:8098
      - homepage.description=CAdvisor Service
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"
      - "com.centurylinklabs.watchtower.enable=true"

  prometheus-exporter:
    container_name: prometheus-exporter
    hostname: prometheus-exporter
    image: ekofr/pihole-exporter:latest
    restart: unless-stopped
    volumes:
      - /etc/hosts:/etc/hosts:ro
    ports:
      - 9617:9617
    environment:
      - PORT=9617
      - INTERVAL=10s
      - PIHOLE_API_TOKEN=${PIHOLE_API_TOKEN}
      - PIHOLE_HOSTNAME=pihole.lan
    labels:
      - homepage.group=Containers
      - homepage.name=Prometheus Exporter
      - homepage.href=http://192.168.1.201:9617
      - homepage.description=Prometheus Exporter Service
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  prometheus_config:
  prometheus_data:
  grafana_data:
