# PostgreSQL - https://www.postgresql.org
version: "3.9"

services:
  db:
    env_file:
      - ${DOCKER_ENV}/postgres.env
   image: postgres:alpine
   container_name: postgres
   restart: unless-stopped
   volumes:
     - db-data:/var/lib/postgresql/data
   expose:
     - 5432
   labels:
     - "diun.enable=true"
     - "diun.watch_repo=true"
     - "diun.include_tags=alpine"

volumes:
  db-data:
