# AdGuardHome - https://github.com/AdguardTeam/AdGuardHome/wiki/Docker
version: "3.9"

services:
  adguardhome:
    image: adguard/adguardhome:latest
    restart: unless-stopped
    container_name: adguardhome
    command: "-p 3000 -c /opt/adguardhome/conf/AdGuardHome.yaml"
    network_mode: "host"
    volumes:
      - "adguardhome_data:/opt/adguardhome/data"
      - "adguardhome_conf:/opt/adguardhome/conf"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - homepage.group=Containers
      - homepage.name=Adguard Home Ad Blocker
      - homepage.href=http://adguardhome.lan
      - homepage.description=AdGuard Home edition service
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"

volumes:
  adguardhome_data:
  adguardhome_conf:
