version: "3.3"

services:
  ytdl-ui:
    restart: unless-stopped
    container_name: ytdl-ui
    depends_on:
      - ytdl-mongo-db
    volumes:
      - "appdata:/app/appdata"
      - "audio:/app/audio"
      - "video:/app/video"
      - "subscriptions:/app/subscriptions"
      - "users:/app/users"
    ports:
      - "3014:17442"
    image: tzahi12345/youtubedl-material:latest
    labels:
      - homepage.group=Containers
      - homepage.name=Youtube Downloader
      - homepage.href=http://youtubedl.lan
      - homepage.description=Youtube Downloader Service
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"

  ytdl-mongo-db:
    image: mongo:4.4.19
    logging:
      driver: "none"
    container_name: ytdl-mongo-db
    restart: unless-stopped
    volumes:
      - "mongo_data:/data/db"
      - "config_data:/data/configdb"
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=4.4.19"

volumes:
  mongo_data:
  config_data:
  users:
  subscriptions:
  video:
  audio:
  appdata:
