version: "3.3"

services:
  db:
   image: postgres:alpine
   container_name: postgres
   environment:
     - POSTGRES_USER=db
     - POSTGRES_PASSWORD=mypassword
     - POSTGRES_DB=db
   restart: unless-stopped
   volumes:
     - db-data:/var/lib/postgresql/data
   expose:
     - 5432
   labels:
     - "diun.enable=true"
     - "diun.watch_repo=true"
     - "diun.include_tags=alpine"

volumes:
  db-data:
