# Unbound DNS Server - https://hub.docker.com/r/cdrocker/unbound
version: "3.9"

services:
  unbound-dns:
    environment:
      - TZ=Europe/London
    restart: unless-stopped
    container_name: unbound-dns
    hostnane: unbound-dns
    image: cdrocker/unbound:latest
    volumes:
      - 'unbound-data:/etc/unbound/conf.d/'
    ports:
      - "5300:5300/udp"
      - "5300:5300/tcp"
    cap_add:
      - NET_ADMIN
    networks:
      - proxy
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"
      - "traefik.enable=true"
      - "traefik.tcp.routers.unbound.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.unbound.entrypoints=dns"
      - "traefik.tcp.routers.unbound.service=unbound-dns"
      - "traefik.tcp.services.unbound-dns.loadbalancer.server.port=5300"

volumes:
  unbound-data:

networks:
  proxy:
    external: true
  infrastructure:
    external: true
