# Lighttpd  - https://www.lighttpd.net/ 
version: "3.9"

services:
  lighttpd:
    image: jitesoft/lighttpd:latest
    container_name: lighttpd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - lighttpd_config:/usr/local/etc/lighttpd
    ports:
      - "80:80"
    restart: unless-stopped
    labels:
      - homepage.group=Containers
      - homepage.name=Lighttpd
      - homepage.href=https://www.lighttpd.net/
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=latest"

volumes:
  lighttpd_config:
