#!/bin/bash

fromver="version: \"$1\""
tover="version: \"$2\""

echo "Moving from $fromver to $tover"
echo ""

for filename in docker-compose*.yml; do
	[ -e "$filename" ] || continue

	echo "$filename"

	while IFS='' read -r a; do
		echo "${a//$fromver/$tover}"
	done <"$filename" >"$filename.t"
	mv "$filename.t" "$filename"
done
