#!/bin/bash
export DOCKER_ENV="$HOME/docker/environment"
export DOCKER_PRIV_ENV="$HOME/docker-private"
export PUID="$UID"
export PGID="$UID"

envfile="$DOCKER_ENV/$1.env"
privenvfile="$DOCKER_PRIV_ENV/$1.env"
composefile="$HOME/docker/compose/docker-compose-$1.yml"
stackname="$1-stack"
cmd="$2"
params=""

if [ ! -z "$3" ]
then
  composefile="$HOME/docker/compose/docker-compose-$2.yml"
  cmd="$3"
fi

if [ "$cmd" = "up" ]
then
  params="-d"
fi

if [ ! -e "$envfile" ]
then
  envfile="$DOCKER_ENV/global.env"
fi

if [ -e "$privenvfile" ]
then
  envfile="$privenvfile"
fi

echo ""
echo Stack·name:·$stackname

if [ -e "$composefile" ]
then
  echo Using compose file: $composefile
  echo Reading environment from: $envfile

  case $cmd in
   ip)
    echo ""
    for containerid in $(docker-compose -p $stackname -f $composefile --env-file $envfile ps -q);
    do
     ipaddress=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $containerid)
     containername=$(docker inspect -f "{{.Name}}" $containerid)

       if [ "$ipaddress" = "" ]
       then
         ipaddress="0.0.0.0"
       fi

     echo $containername  =  $ipaddress
    done

    echo "" ;;
   restart)
    docker-compose -p $stackname -f $composefile \
                   --env-file $envfile \
                   stop

    echo Waiting 10s second before restart like all good
    echo Turn it off and on again routines.

    sleep 10s

    docker-compose -p $stackname -f $composefile \
                   --env-file $envfile \
                   up -d ;;
  debug)
     docker-compose -p $stackname -f $composefile \
                 --env-file $envfile \
                up ;;
  nuke)
    docker-compose -p $stackname -f $composefile \
                --env-file $envfile \
                stop

    docker-compose -p $stackname -f $composefile \
                --env-file $envfile \
                rm ;;
  *)
     docker-compose -p $stackname -f $composefile \
                 --env-file $envfile \
                $cmd $params ;;
  esac

else
  echo Cannot find compose file: $composefile
  echo Aborting
fi

echo ""
