#!/bin/bash
export DOCKER_ENV="$HOME/docker/environment"

envfile="$DOCKER_ENV/$1.env"
composefile="$HOME/docker/compose/docker-compose-$1.yml"
stackname="$1-stack"
cmd="$2"
params=""

if [ ! -z "$3" ]
then
  composefile="$HOME/docker/compose/docker-compose-$2.yml"
  cmd="$3"
fi

if [ "$cmd" = "up" ]
then
  params="-d"
fi

if [ ! -e "$envfile" ]
then
  envfile="$DOCKER_ENV/global.env"
fi

echo ""
echo Stack·name:·$stackname

if [ -e "$composefile" ]
then
  echo Using compose file: $composefile
  echo Reading environment from: $envfile

  if [ "$cmd" = "restart" ]
  then

    docker-compose -p $stackname -f $composefile \
                   --env-file $envfile \
                   stop

    echo Waiting 10s second before restart like all good
    echo Turn it off and on again routines.

    sleep 10s

    docker-compose -p $stackname -f $composefile \
                   --env-file $envfile \
                   up -d
  else
    docker-compose -p $stackname -f $composefile \
               --env-file $envfile \
               $cmd $params
  fi

else
  echo Cannot find compose file: $composefile
  echo Aborting
fi

echo ""
