#!/bin/bash

if [ "$DOCKER_COMPOSE_FOLDER" = "" ]; then
echo  "CRITICAL: Environment varable DOCKER_COMPOSE_FOLDER must be set to the folder containing the compose files."
 exit 1
fi

if [ "$DOCKER_ENV" = "" ]; then
echo "CRITICAL: Environment varable DOCKER_ENV must be set to the folder containing the environment files"
exit 1
fi

if [ "$DOCKER_SECRET_ENV" = "" ]; then
 echo "CRITICAL: Environment variable DOCKER_SECRET_ENV must be set to the folder containing the secrets"
exit 1
fi

export DOCKER_GATEWAY_HOST=$(ip addr show dev eth0 | grep 'state UP' -A2 | tail -n1 | awk -F'[/ ]+' '{print $3}')
export PUID="$UID"
export PGID="$UID"

projectid="${1^^}_"

function getkeys()
{
  while IFS='=' read -r key value
  do
    dkey="$projectid"
    echo "      - ${key#${projectid}}=\${$key}"
  done < "$1"
}

globalenvfile="$DOCKER_ENV/global.env"
envfile="$DOCKER_ENV/$1.env"
privenvfile="$DOCKER_SECRET_ENV/$1.env"
composefile="$HOME/docker/compose/docker-compose-$1.yml"
stackname="$1-stack"
   
echo "    environment:"

  if [ -e "$globalenvfile" ]
  then
    getkeys "$globalenvfile"
  fi

  if [ -e "$envfile" ]
  then
    getkeys "$envfile"
  fi

  if [ -e "$privenvfile" ]
  then
    getkeys "$privenvfile"
  fi

